USE Diablo


SELECT TOP(50) Name ,FORMAT(Start,'yyyy-MM-dd') AS Start
FROM Games
WHERE DATEPART(YEAR,Start) BETWEEN 2011 AND 2012
ORDER BY Start,Name
 
--SELECT TOP(50) Name ,CONVERT(DATE,Start,101) AS Start
-- FROM Games
-- WHERE DATEPART(YEAR,Start) BETWEEN 2011 AND 2012
-- ORDER BY Start,Name
 