USE Diablo

SELECT Name AS Game,
CASE
WHEN DATEPART(HOUR,Start) BETWEEN 0 AND 11 THEN 'Morning'
WHEN DATEPART(HOUR,Start) BETWEEN 12 AND 17 THEN 'Afternoon'
WHEN DATEPART(HOUR,Start) BETWEEN 17 AND 23 THEN 'EVNING'
END AS [Part of the Day],
CASE
WHEN Duration BETWEEN 1 AND 3 THEN 'Extra Short'
WHEN Duration BETWEEN 4 AND 6 THEN 'Short'
WHEN Duration >6 THEN 'Long'
WHEN Duration IS NULL THEN 'Extra Long'
END AS DURATION
 FROM Games
ORDER BY Game,DURATION,[Part of the Day]


